### ISSUE TITLE
Feature Request - Chiptune/Multitrack support

### ISSUE THREAD

**Issue by tracker1** [Aveek-Saha/MusicPlayer#10]
Would be cool to be able to playback scene/multitrack audio.  It looks like there's already a chiptune module that could be on the node side to pass a PCM stream to the audio player component.

https://github.com/Guichaguri/node-chiptune

**Comment by Aveek-Saha** [comment]
It seems like there is a library similar to Howler for chiptune, called [chiptune.js](https://github.com/deskjet/chiptune2.js). Dusk Player is closely integrated with the howler library, and adding support for chiptune would mean changing the entire player back-end. 
So as of now I don't think this will be possible.
