### ISSUE TITLE
Recursive song library

### ISSUE THREAD

**Issue by sarbikbetal** [Aveek-Saha/MusicPlayer#11]
Can you please add a feature so as to recursively retrieve all the music files inside that directory (I mean search inside all the the sub-folders) and list them.

**Comment by sarbikbetal** [comment]
Check out this Gist and implement the feature accordingly 
[https://gist.github.com/kethinov/6658166](url)

**Comment by Aveek-Saha** [comment]
I'll check it out

**Comment by Aveek-Saha** [comment]
This feature has been added, and will be included in the next release of Dusk Player.
