### ISSUE TITLE
Progress bar has a transition

### ISSUE THREAD

**Issue by talentlessguy** [Aveek-Saha/MusicPlayer#14]
It shouldn't. When I click on some moment of a song the pointer should instantly move to that moment.

`.progress-bar` is causing the issue, it has `transition: .4s` built-in. I tried to overwrite with `!important` but it didn't help by some reason

**Comment by Aveek-Saha** [comment]
I don't completely agree that there shouldn't be a transition on the progress bar. While it's true that it currently takes far too long for the bar to transition to where the user clicks, without a transition, instantaneously moving the bar would be jarring.

I will look into how to make the transition feel more responsive.

**Comment by Aveek-Saha** [comment]
It should be fixed in the latest commit
