### ISSUE TITLE
Nightly builds

### ISSUE THREAD

**Issue by talentlessguy** [Aveek-Saha/MusicPlayer#15]
There are some bugs that already fixed but new version is not yet released. I know that there may be experimental features so my suggestion is to release nighly / beta builds which are newer than regular releases but contain new features

**Comment by Aveek-Saha** [comment]
The thing about nightly builds is that I don't really update the application that often. I generally fix bugs and add new features in a short span of time and then create a new release soon after. So I'm not sure if nightly builds will help.

**Comment by talentlessguy** [comment]
@Aveek-Saha yes you don't but some bugs are fixed but I have problems with building it on my local machine (C++ postinstall stuff). Also it takes time to install and build it.

I think releasing builds with bugs is a good idea instead of waiting for release of stable version or building by yourself

**Comment by Aveek-Saha** [comment]
I'll see what I can do about that, I'll try releasing new features faster, but if it's too buggy the user experience will suffer.
