### ISSUE TITLE
Themes don't switch

### ISSUE THREAD

**Issue by talentlessguy** [Aveek-Saha/MusicPlayer#17]
DuskPlayer version: 4
Electron version: 4.2.12
OS: Manjaro Linux

![wtf](https://user-images.githubusercontent.com/35937217/69007542-07232980-0950-11ea-9fcc-2121291bce02.gif)

**Comment by Aveek-Saha** [comment]
You have to restart to change themes, I'll add that somewhere so that it's more clear

**Comment by talentlessguy** [comment]
@Aveek-Saha thanks for claryfing

the best option imo is to attach `alert("You need to restart")` to switch handler
