### ISSUE TITLE
Track title is not being changed when switching to prev track

### ISSUE THREAD

**Issue by talentlessguy** [Aveek-Saha/MusicPlayer#18]
Here's how it works now:

![20191119140551-7c011ad592 gif-2-mp4 com](https://user-images.githubusercontent.com/35937217/69141423-cce39480-0ad5-11ea-9187-bdd3ff19e662.gif)

**Comment by Aveek-Saha** [comment]
This issue has been fixed in 9498e020c5c94309cc3ee7385cea70274a8ab580 along with the rework of the metadata display.
