### ISSUE TITLE
Mac build

### ISSUE THREAD

**Issue by Aveek-Saha** [Aveek-Saha/MusicPlayer#3]
**Summary**
I don't own an Apple device, so I can't build this application for MacOs

**Details**
I would really appreciate it if someone would clone the repository and generate the build for MacOs. It should be as simple as running ```npm install``` from the root folder, and then doing ```npm run dist ```

**Comment by CodeF0x** [comment]
Hi! Is this still an issue? Because I'd be glad to help!

**Comment by Aveek-Saha** [comment]
Yes, this is still an issue, I still don't own any devices that run MacOS. Help is appreciated!

**Comment by CodeF0x** [comment]
Do you have a 512x512 icon? I can't use 512x512.png from the repository, as it also has only 256x256 pixels.

![Bildschirmfoto 2019-11-15 um 23 04 37](https://user-images.githubusercontent.com/33719652/68978997-9c150e00-07fc-11ea-8168-0877ceff467d.png)

**Comment by Aveek-Saha** [comment]
Sorry about that, I'll put the 512x512 image here. Also I think it makes sense to wait for version 4.0.0 before you build it, because I'll be releasing that soon, so all the latest features can be included!

![512x512](https://user-images.githubusercontent.com/31800695/68988015-c7c4e200-0856-11ea-9e64-d64f9d844a57.png)

**Comment by CodeF0x** [comment]
Sure, and thanks for the icon! Just ping me here when you need the Mac build! 😃

**Comment by Aveek-Saha** [comment]
So I've just released version 4 for windows and linux, you can go ahead with the mac build!

**Comment by CodeF0x** [comment]
I was able to sucessfully build it. However, the app is not functional on Mac :(.

The menu doesn't get displayed properly and the few actions that are displayed, don't work. 
On both my Windows and Ubuntu machine it gets displayed correctly and also works, except for the theme toggler (nothing changes when I click, but I think that's for another issue).


![DuskPlayer broken](https://user-images.githubusercontent.com/33719652/68998227-e60afc00-08af-11ea-8c62-b9836c84a113.gif)

**Comment by Aveek-Saha** [comment]
Oh that's unfortunate. Looks like a mac build won't be possible as of now. As for the theme toggling, you have to to restart the application for the new theme to show, I should probably mention that somewhere.
But anyway, thanks for the help!

**Comment by CodeF0x** [comment]
I think I will fork the repository and try to implement a proper menu on Mac. 

For the theme I'm sorry, I don't know how I couldn't come up with the idea to simply restart the application 😅.

**Comment by CodeF0x** [comment]
Great news! I got the menus to work with mac! 
I submitted a pull request.

GitHub doesn't allow files bigger than 10 MB to be attached to comments, so [here's](https://drive.google.com/drive/folders/1HyBGuLpySpSssrR5hJ7cr3SVvsRIuqcv?usp=sharing) the download link to the DMG file.

**Comment by Aveek-Saha** [comment]
That's great! I'll add it to the new release.

**Comment by talentlessguy** [comment]
time to close it?
