### ISSUE TITLE
Add keyboard shortcuts for playback

### ISSUE THREAD

**Issue by Aveek-Saha** [Aveek-Saha/MusicPlayer#31]
**Is your feature request related to a problem? Please describe.**
Users should be able to use intuitive shortcuts to control media playback on the player

**Describe the solution you'd like**
Capture certain keystrokes as shortcuts

**Describe alternatives you've considered**
Media specific keys present on keyboards can also work (Some keyboards have dedicated media keys)

**Comment by ielixirz** [comment]
can I take on this thanks !

**Comment by Aveek-Saha** [comment]
Sure, create a fork and then make changes to the **keyboard_shortcut** branch.
Do you have any prior experience with electron?

**Comment by ielixirz** [comment]
no, I don't 
but I can run the app locally and still got no issue so far, currently working on testing with the media keys 

if you have any suggestion feel free to inform me, I'm quite new to the community thanks

**Comment by ielixirz** [comment]
btw I forked the repo and already pushed my branch, do you want me to use your branch 'keyboard_shortcut' ?
or it is ok to use my branch to create pr.

https://github.com/ielixirz/MusicPlayer/tree/feat/handle-shortcut-keys/31

**Comment by Aveek-Saha** [comment]
Here is some documentation that might be useful: https://www.electronjs.org/docs/tutorial/keyboard-shortcuts

Try to use intuitive shortcuts, for example, spacebar to play/pause, right arrow key to play next, left arrow key for previous song, and up/down keys for volume control.

**Comment by ielixirz** [comment]
> Here is some documentation that might be useful: https://www.electronjs.org/docs/tutorial/keyboard-shortcuts
> 
> Try to use intuitive shortcuts, for example, spacebar to play/pause, right arrow key to play next, left arrow key for previous song, and up/down keys for volume control.
> 
> You can use your branch, but raise the pr to the keyboard_shortcut branch of this repo

got it.

**Comment by ielixirz** [comment]
@Aveek-Saha I raised pr to your branch, you can check it out.

**Comment by ielixirz** [comment]
@Aveek-Saha I raised pr to your branch, you can check it out.

**Comment by Aveek-Saha** [comment]
I'll run some tests to see if it works as expected, if there are no issues I'll merge your PR.
