### ISSUE TITLE
Music does not pause 

### ISSUE THREAD

**Issue by hebertcisco** [Aveek-Saha/MusicPlayer#35]
My first experience was strange, I searched for the songs in the directories, started playing and didn't want to pause!

1. Open the application via `.Appimage`
2. Search your music in the directories
3. Put it to play
4. Try to move the application window to a secondary screen
5. See error

When trying to use the application with two screens, it seems that the application opens twice, this is strange, as it does not stop the music when clicking on the pause button.

 - OS: Ubuntu 20.04
 - Application Version: 5.0

**Comment by Aveek-Saha** [comment]
Not sure why this behavior is happening, does it happen if you use only one display?
