### ISSUE TITLE
[Feature-Request]: User-submitted styles/themes

### ISSUE THREAD

**Issue by jhdcruz** [Aveek-Saha/MusicPlayer#6]

**Comment by Aveek-Saha** [comment]
It would be possible for users to customise the interface by providing their own player.html files along with custom css. Themes could be selected from the menu.

**Comment by jhdcruz** [comment]
> It would be possible for users to customise the interface by providing their own player.html files along with custom css. Themes could be selected from the menu.
> Open to suggestions.

Maybe building a website or some kind of forums where they can share it?

**Comment by jhdcruz** [comment]
Thanks :+1:
